name: Testing QoSenforce smart contract deployed to IBM cloud over k8s
version: "2.0.0"

info:
  Version: HLF 2.2.x over IBM K8s cluster
  Size: 2 Orgs with 2 Peers
  Orderer: Raft
  Distribution: 3 orderers
  StateDB: CouchDB

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
    - id: slaDR

organizations:
  - mspid: Org1MSP
    identities:
      wallet:
        path: 'networks/Wallet'
        adminNames:
        - Org1Admin
    connectionProfile:
      path: 'networks/connection.json'
      discover: true