{
 "title": "Hyperledger Caliper (Unofficial",
 "description": "An unofficial dashboard for Transaction metrics by Hyperledger Caliper",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Caliper Latency Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency Histogram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (caliper_tx_e2e_latency_bucket{final_status=\"success\"})"
    }
   ]
  },
  { "title": "Caliper TPS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Submitted TXs (Per Worker)",
   "type": "graph",
   "description": "Worker Specific Submitted TXs ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(caliper_tx_submitted[10s])"
    }
   ]
  },
  {
   "title": "Finished TXs (Successful and Failed)",
   "type": "graph",
   "description": "Worker Specific Finished TXs (Successful and Failed)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(caliper_tx_finished[10s])" }
   ]
  },
  {
   "title": "Total Successful TXs per Second",
   "type": "graph",
   "description": "Sum of Successful transactions for all workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(caliper_tx_finished{final_status=\"success\"}[10s]))"
    }
   ]
  },
  {
   "title": "Total Successful TXs",
   "type": "graph",
   "description": "Sum of Successful transactions for all workers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (caliper_tx_finished{final_status=\"success\"})"
    }
   ]
  },
  {
   "title": "Total Failed TXs per Second",
   "type": "graph",
   "description": "Sum of failed transactions for all workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(caliper_tx_finished{final_status=\"failed\"}[10s]))"
    }
   ]
  },
  {
   "title": "Total Failed TXs",
   "type": "graph",
   "description": "Sum of failed transactions for all workers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (caliper_tx_finished{final_status=\"failed\"})"
    }
   ]
  },
  {
   "title": "Total Submitted vs Finished TXs per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(caliper_tx_submitted[10s]))",
     "legendFormat": "Submited"
    },
    {
     "expr": "sum by (job) (rate(caliper_tx_finished[10s]))",
     "legendFormat": "Finished"
    }
   ]
  },
  {
   "title": "Total Submitted vs Finished TXs per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) ((caliper_tx_submitted))",
     "legendFormat": "Submited"
    },
    {
     "expr": "sum by (job) ((caliper_tx_finished))",
     "legendFormat": "Finished"
    }
   ]
  }
 ]
}