#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create org2peer1
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org2_name }}"
    organization_msp_id: "{{ org2_msp_id }}"
    ca_name: "{{ org2_ca_name }}"
    peer_name: "{{ org2_peer1_name }}"
  vars_files:
    - common-vars.yml
    - org2-vars.yml
  roles:
    - ibm.blockchain_platform.endorsing_organization

- name: Create org2peer1
  hosts: localhost
  vars:
    state: present
    organization_name: "{{ org2_name }}"
    organization_msp_id: "{{ org2_msp_id }}"
    ca_name: "{{ org2_ca_name }}"
    peer_name: "{{ org2_peer2_name }}"
  vars_files:
    - common-vars.yml
    - org2-vars.yml
  roles:
    - ibm.blockchain_platform.endorsing_organization
