#
# SPDX-License-Identifier: Apache-2.0
#
---
api_endpoint: https://0bd9fae9a7cb4dc39b058f1e6851c82b-ibpconsole-console.uss02.blockchain.cloud.ibm.com
api_authtype: ibmcloud
api_key: A1XQyQIf5lLZ9QaVvWOdWrN470mqScmVYwLZP0boL_sc
ca_admin_enrollment_id: admin
ca_admin_enrollment_secret: adminpw
organization_admin_enrollment_id: orderingorgadmin
organization_admin_enrollment_secret: orderingorgadminpw
ordering_service_enrollment_id: orderingorgorderer
ordering_service_enrollment_secret: orderingorgordererpw
ordering_service_msp: OrdererMSP
ordering_service_nodes: 3
wait_timeout: 600
