#
# SPDX-License-Identifier: Apache-2.0
#
---
api_endpoint: https://0bd9fae9a7cb4dc39b058f1e6851c82b-ibpconsole-console.uss02.blockchain.cloud.ibm.com
api_authtype: ibmcloud
api_key: A1XQyQIf5lLZ9QaVvWOdWrN470mqScmVYwLZP0boL_sc
ca_admin_enrollment_id: admin
ca_admin_enrollment_secret: adminpw
organization_admin_enrollment_id: org1admin
organization_admin_enrollment_secret: org1adminpw
peer_enrollment_id: org1peer
peer_enrollment_secret: org1peerpw
application_enrollment_id: org1app
application_enrollment_secret: org1apppw
application_enrollment_type: client
application_max_enrollments: 10
org1_ca_name: "Org1 CA"
org1_peer1_name: "Org1 Peer1"
org1_peer2_name: "Org1 Peer2"
wait_timeout: 600
