global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rules.yml"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 5s
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'BlockchainSmartContract'
    scrape_interval: 1s
    static_configs:
      - targets: ['orderer.example.com:8444', 'peer0.org1.example.com:9444', 'peer0.org2.example.com:9445']

  - job_name: 'BenchmarkingWorkers'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:3001', 'localhost:3002', 'localhost:3003', 'localhost:3004']


alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - '46.101.250.30:9093'